# Generated by Django 4.2.30 on 2026-10-01 21:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Articulo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=160)),
                ("slug", models.SlugField(max_length=160)),
                ("resumen", models.CharField(max_length=300)),
                ("contenido", models.TextField(help_text="HTML del artículo")),
                ("categoria", models.CharField(max_length=60)),
                (
                    "palabra_clave",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Palabra clave SEO"
                    ),
                ),
                ("icono", models.CharField(blank=True, max_length=8)),
                ("minutos_lectura", models.PositiveSmallIntegerField(default=5)),
                ("destacado", models.BooleanField(default=False)),
                ("publicado", models.BooleanField(default=True)),
                (
                    "fecha_publicacion",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
            ],
            options={
                "verbose_name": "Artículo",
                "verbose_name_plural": "Artículos",
                "ordering": ["-destacado", "-fecha_publicacion", "titulo"],
            },
        ),
        migrations.CreateModel(
            name="Sitio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=80)),
                ("slug", models.SlugField(max_length=80, unique=True)),
                ("eslogan", models.CharField(max_length=160)),
                (
                    "descripcion",
                    models.TextField(help_text="Texto de presentación de la web"),
                ),
                (
                    "nicho",
                    models.CharField(
                        help_text='Temática principal, p. ej. "Inteligencia artificial"',
                        max_length=120,
                    ),
                ),
                (
                    "icono",
                    models.CharField(
                        help_text="Emoji que identifica la web", max_length=8
                    ),
                ),
                (
                    "color_primario",
                    models.CharField(
                        default="#2f89fc",
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^#[0-9a-fA-F]{6}$",
                                "Usa un color hexadecimal, p. ej. #2f89fc",
                            )
                        ],
                    ),
                ),
                (
                    "color_secundario",
                    models.CharField(
                        default="#0f172a",
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^#[0-9a-fA-F]{6}$",
                                "Usa un color hexadecimal, p. ej. #2f89fc",
                            )
                        ],
                    ),
                ),
                (
                    "por_que",
                    models.TextField(
                        help_text="HTML con los datos de la investigación",
                        verbose_name="Por qué es tendencia",
                    ),
                ),
                (
                    "fuentes",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Lista de {"titulo": ..., "url": ...}',
                    ),
                ),
                ("orden", models.PositiveSmallIntegerField(default=0)),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Sitio",
                "verbose_name_plural": "Sitios",
                "ordering": ["orden", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="Tendencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=120)),
                ("slug", models.SlugField(max_length=120)),
                ("descripcion", models.TextField(help_text="HTML breve")),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("emergente", "Emergente"),
                            ("en_auge", "En auge"),
                            ("consolidada", "Consolidada"),
                        ],
                        default="en_auge",
                        max_length=20,
                    ),
                ),
                (
                    "dato",
                    models.CharField(
                        blank=True,
                        help_text='p. ej. "+4.300 % en búsquedas"',
                        max_length=80,
                        verbose_name="Dato clave",
                    ),
                ),
                ("fuente", models.CharField(blank=True, max_length=120)),
                ("fuente_url", models.URLField(blank=True)),
                ("icono", models.CharField(blank=True, max_length=8)),
                ("orden", models.PositiveSmallIntegerField(default=0)),
                (
                    "articulo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tendencias",
                        to="nichos.articulo",
                    ),
                ),
                (
                    "sitio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tendencias",
                        to="nichos.sitio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tendencia",
                "verbose_name_plural": "Tendencias",
                "ordering": ["orden", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=140)),
                ("slug", models.SlugField(max_length=140)),
                ("marca", models.CharField(blank=True, max_length=80)),
                ("categoria", models.CharField(max_length=60)),
                ("icono", models.CharField(blank=True, max_length=8)),
                ("resumen", models.CharField(max_length=300)),
                (
                    "contenido",
                    models.TextField(blank=True, help_text="HTML del análisis"),
                ),
                ("ideal_para", models.CharField(blank=True, max_length=160)),
                ("precio_orientativo", models.CharField(blank=True, max_length=60)),
                (
                    "puntuacion",
                    models.DecimalField(
                        decimal_places=1,
                        default=0,
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                ("pros", models.JSONField(blank=True, default=list)),
                ("contras", models.JSONField(blank=True, default=list)),
                ("especificaciones", models.JSONField(blank=True, default=dict)),
                (
                    "enlace",
                    models.URLField(
                        blank=True, verbose_name="Enlace de compra o afiliado"
                    ),
                ),
                ("destacado", models.BooleanField(default=False)),
                ("publicado", models.BooleanField(default=True)),
                (
                    "sitio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="productos",
                        to="nichos.sitio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Producto",
                "verbose_name_plural": "Productos",
                "ordering": ["-destacado", "-puntuacion", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="Comparativa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=160)),
                ("slug", models.SlugField(max_length=160)),
                ("resumen", models.CharField(max_length=300)),
                ("introduccion", models.TextField(help_text="HTML antes de la tabla")),
                ("columnas", models.JSONField(default=list)),
                ("filas", models.JSONField(default=list)),
                ("ganador", models.CharField(blank=True, max_length=120)),
                ("veredicto", models.TextField(help_text="HTML con la conclusión")),
                ("icono", models.CharField(blank=True, max_length=8)),
                ("destacado", models.BooleanField(default=False)),
                ("publicado", models.BooleanField(default=True)),
                (
                    "fecha_publicacion",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                (
                    "productos",
                    models.ManyToManyField(
                        blank=True, related_name="comparativas", to="nichos.producto"
                    ),
                ),
                (
                    "sitio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comparativas",
                        to="nichos.sitio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Comparativa",
                "verbose_name_plural": "Comparativas",
                "ordering": ["-destacado", "-fecha_publicacion", "titulo"],
            },
        ),
        migrations.AddField(
            model_name="articulo",
            name="sitio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="articulos",
                to="nichos.sitio",
            ),
        ),
        migrations.AddConstraint(
            model_name="tendencia",
            constraint=models.UniqueConstraint(
                fields=("sitio", "slug"), name="tendencia_slug_unico_por_sitio"
            ),
        ),
        migrations.AddConstraint(
            model_name="producto",
            constraint=models.UniqueConstraint(
                fields=("sitio", "slug"), name="producto_slug_unico_por_sitio"
            ),
        ),
        migrations.AddConstraint(
            model_name="comparativa",
            constraint=models.UniqueConstraint(
                fields=("sitio", "slug"), name="comparativa_slug_unico_por_sitio"
            ),
        ),
        migrations.AddConstraint(
            model_name="articulo",
            constraint=models.UniqueConstraint(
                fields=("sitio", "slug"), name="articulo_slug_unico_por_sitio"
            ),
        ),
    ]
